empa-scientific-it/python-tutorial

- tutorial/tests/testsuite.py
> Replace `lstrip` with string slicing.

- magic_example.ipynb
- tutorial/tests/testsuite.py
Fixes #30 
* Handle VS Code behavior
* Optionally specify the module name as the cell magic's argument
> More robust lookup of test module file

- magic_example.ipynb
- tutorial/tests/test_magic_example.py
- tutorial/tests/testsuite.py
Only solution functions defined in the current cell will be tested
> Fix testsuite and user namespace bug

- control_flow.ipynb
- functions.ipynb
- slides/control_flow_slides.ipynb
- slides/functions_slides.ipynb
- tutorial/functions.py
- tutorial/tests/test_control_flow.py
Fixes #51 
Removes annotations and other markup for creating slides. Retain the slides-ready notebook in `slides/`, at the moment.
> Fix and cleanup slides

- tutorial/tests/test_input_output.py
> Fixed test of exercise2.

- README.md
> Extend Readme on how-to run tutorial locally

- basic_datatypes.ipynb
> Fix exercise 3 on strings.

- intro.ipynb
> Request participants to use Binder only.

- object_oriented_programming.ipynb
- tutorial/tests/test_object_oriented_programming.py
Fix a bug in the test function of the "N-body problem" exercise. The `function_to_test` was not passed the correct argument
> Bugfix to OOP exercise test

- control_flow.ipynb
- tutorial/tests/test_control_flow.py
> Control flow: add some intermediate exercises

- functional_programming.ipynb
- input_output.ipynb
- tutorial/functional_programming.py
- tutorial/tests/test_functional_programming.py
- tutorial/tests/test_input_output.py
Added some intermediate exercises on input and output.
> Input-output and functional programming: add intermediate exercises

- input_output.ipynb
- tutorial/tests/test_input_output.py
> Fix tests to I/O exercises

- control_flow.ipynb
- tutorial/tests/test_control_flow.py
> Fix exercises on control flow

- input_output.ipynb
Some intermediate exercises had ambiguities which I now fixed.
> Improved description of exercises

- magic_example.ipynb
- tutorial/tests/test_magic_example.py
- tutorial/tests/testsuite.py
- tutorial/tests/testsuite_exceptions.py
- tutorial/tests/testsuite_helpers.py
> Allow asynchronous testing

- library_scipy.ipynb
- tutorial/tests/test_library_scipy.py
redefined fitting parameters so that they don't appear in the denominator -- this was causing some problems.
> Fixed the bug in the Gaussian exercise.

- threads.ipynb
- tutorial/tests/test_threads.py
> Fix first exercise on mutltiprocessing

- library_pandas.ipynb
> Fix errors in Pandas notebook

- object_oriented_programming.ipynb
- tutorial/object_oriented_programming.py
- tutorial/tests/test_object_oriented_programming.py
Fixes:
- #208 
- #111 
- #212 
As mentioned in #207
> OOP: added quiz, 3rd exercise and updated tests

- functions.ipynb
- tutorial/common.py
- tutorial/tests/test_functions.py
- tutorial/tests/test_functions_advanced.py
- tutorial/tests/testsuite/helpers.py
> Functions: test keyword parameter

- basic_datatypes.ipynb
- tutorial/tests/test_basic_datatypes.py
> Fix different issues in datatypes notebook

- control_flow.ipynb
- tutorial/control_flow.py
- tutorial/tests/test_control_flow.py
> Control flow: add quizzes

- modules_and_packages.ipynb
> Add a small section describing the `pyproject.toml` file

- manage_python_project.ipynb
> Add a section on different package managers

- README.md
- tutorial/tests/test_control_flow.py
Remove incorrect line about updating conda environment.
> Fix README file

- modules_and_packages.ipynb
Fixes https://github.com/empa-scientific-it/python-tutorial/issues/241
> Address minor issues in the "modules and packages" notebook

- tutorial/tests/testsuite/testsuite.py
> Fix debug mode persistency issue

- .github/workflows/build-docker-image.yml
From 2023.06.0 to 2024.03.0 (latest stable)
> Upgrade repo2docker version

- .gitignore
- tutorial/tests/testsuite/ai_helpers.py
Update to most recent/stable models that support structured outputs
> Update OpenAI models

- .github/workflows/docker-build.yml
Run only if Dockerfile or any file related is changed. Do not automatically run if notebooks' content is updated, since that update can be easily pulled via git.
> Change GitHub workflow
